import { Dimensions, StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'

const { width: SCREEN_WIDTH } = Dimensions.get('window')

const HERO_HEIGHT = Math.round(SCREEN_WIDTH * (3 / 4))

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  heroImage: {
    width: '100%',
    height: HERO_HEIGHT,
  },
  scroll: { flex: 1 },
  card: {
    backgroundColor: colors.background,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  errorText: { color: colors.red, fontSize: 16, textAlign: 'center' },
  headerBtns: { flexDirection: 'row', alignItems: 'center' },
  headerBtn: { paddingHorizontal: 4, paddingVertical: 4, marginRight: 4 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 10,
  },
  titleRowSingleLine: {
    alignItems: 'center',
  },
  favBtn: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -2,
  },
  titleLinkWrap: {
    flex: 1,
  },
  title: {
    flex: 1,
    fontSize: 28,
    fontWeight: '700',
    color: colors.label,
    lineHeight: 34,
  },
  tagRow: {
    flexDirection: 'row',
    gap: 6,
  },
  tagScroll: {
    marginBottom: 12,
  },
  tag: {
    backgroundColor: colors.brandLight,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  tagText: { color: colors.brand, fontSize: 12, fontWeight: '500' },
  allergenBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  allergenBadgePill: {
    flexDirection: 'row',
    backgroundColor: '#fef3c7',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  allergenBadgeText: { fontSize: 12, fontWeight: '500', color: '#92400e' },
  householdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  householdAvatarWrapper: { position: 'relative' },
  servingStepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
    marginBottom: 8,
  },
  servingStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.secondaryBackground,
    borderRadius: 10,
  },
  servingStepperButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  servingStepperValue: {
    minWidth: 44,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.label,
    textAlign: 'center',
  },
  toggleGroup: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.separator,
    marginBottom: 16,
  },
  toggleDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.separator,
  },
  keepScreenRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  keepScreenLabel: { fontSize: 16, color: colors.label },
  fontSizeControl: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fontSizeTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 120,
    position: 'relative',
  },
  fontSizeTrackLine: {
    position: 'absolute',
    left: 10,
    right: 10,
    height: 1.5,
    backgroundColor: colors.separator,
  },
  fontSizeDotWrapper: { flex: 1, alignItems: 'center', paddingVertical: 8 },
  fontSizeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: colors.separator,
    backgroundColor: colors.background,
  },
  fontSizeDotActive: {
    borderColor: colors.blue,
    backgroundColor: colors.blue,
  },
  notesBlock: { marginBottom: 16 },
  notesText: { fontSize: 17, color: colors.secondaryLabel, lineHeight: 22 },
  notesPlaceholder: { color: colors.tertiaryLabel },
  componentBlock: { marginTop: 8 },
  componentName: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.label,
    marginBottom: 0,
    lineHeight: 25,
  },
  section: { marginBottom: 16 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.secondaryLabel,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeaderToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
  },
  sectionToggleIcon: {
    marginBottom: 8,
  },
  addAllText: { fontSize: 13, color: colors.blue },
  addAllDone: { color: colors.green },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  bullet: { color: colors.tertiaryLabel, marginRight: 8, marginTop: 1 },
  ingredientText: { flex: 1, fontSize: 17, color: colors.label, lineHeight: 22 },
  addIngredientBtn: { marginLeft: 8, marginTop: 2 },
  stepRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 14 },
  stepNum: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.blue,
    width: 28,
    marginTop: 1,
  },
  stepBody: { flex: 1 },
  timerSpan: { color: '#d97706', fontWeight: '700' },
  stepText: { fontSize: 17, color: colors.label, lineHeight: 22 },
  stepIngList: {
    marginTop: 8,
    gap: 5,
  },
  stepIngRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  stepIngDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.tertiaryLabel,
    marginTop: 8,
  },
  stepIngItem: {
    flex: 1,
    fontSize: 16,
    lineHeight: 21,
    color: colors.secondaryLabel,
  },
  flex: { flex: 1 },
  headerBackBtn: { flexDirection: 'row', alignItems: 'center', marginLeft: -8 },
  headerBackText: { fontSize: 17, color: colors.label },
  heroEditBtn: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroEditText: { fontSize: 12, color: '#ffffff', fontWeight: '600' },
  heroPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.gray6,
  },
  heroPlaceholderText: { fontSize: 13, color: colors.secondaryLabel },
  titleInput: {
    borderBottomWidth: 1,
    borderColor: colors.opaqueSeparator,
    paddingBottom: 4,
  },
  addTagBtn: {
    borderWidth: 1,
    borderColor: colors.opaqueSeparator,
    borderStyle: 'dashed',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  addTagBtnText: { fontSize: 12, color: colors.secondaryLabel },
  notesInput: {
    borderWidth: 1,
    borderColor: colors.opaqueSeparator,
    borderRadius: 8,
    padding: 8,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  componentNameInput: {
    borderBottomWidth: 1,
    borderColor: colors.opaqueSeparator,
    paddingBottom: 4,
  },
  addRowBtn: { paddingVertical: 8 },
  addRowBtnText: { fontSize: 16, color: colors.blue, fontWeight: '500' },
  stepEditRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginBottom: 8 },
  stepInput: {
    flex: 1,
    fontSize: 17,
    color: colors.label,
    lineHeight: 22,
    borderBottomWidth: 1,
    borderColor: colors.opaqueSeparator,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  stepRemoveBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 3,
  },
  stepRemoveText: { fontSize: 16, color: '#fff', fontWeight: '600', lineHeight: 20 },
  actionBar: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: colors.separator,
    backgroundColor: colors.background,
  },
  secondaryBtn: {
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: colors.gray6,
  },
  secondaryBtnText: { fontSize: 16, color: colors.label, fontWeight: '500' },
  primaryBtn: {
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: colors.blue,
  },
  primaryBtnText: { fontSize: 16, color: '#ffffff', fontWeight: '600' },
  btnDisabled: { opacity: 0.5 },
})
