import { StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'

export const styles = StyleSheet.create({
  headerTitleWrap: { flexDirection: 'row', alignItems: 'center', gap: 8, width: '100%' },
  headerTitleText: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.label,
  },
  headerAvatarLoading: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  headerBtns: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  headerBtn: { paddingHorizontal: 4, paddingVertical: 4 },
  floatingAddButton: {
    position: 'absolute',
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  floatingButtonPressed: { opacity: 0.8 },
  screen: { flex: 1, backgroundColor: colors.secondaryBackground },
  // Household switches temporarily replace the list with this loader. Give it an
  // opaque dynamic surface so the navigation container's light fallback never
  // flashes through while the next household's recipes load.
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: colors.secondaryBackground,
  },
  errorText: { color: colors.red, fontSize: 16, textAlign: 'center' },
  tagBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingTop: 0,
    paddingBottom: 16,
  },
  tagBarDivider: {
    width: StyleSheet.hairlineWidth,
    height: 20,
    backgroundColor: colors.opaqueSeparator,
    marginHorizontal: 4,
  },
  tagListContent: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16 },
  nextMealCard: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  nextMealCardPressed: { opacity: 0.7 },
  nextMealImage: { width: 48, height: 48, borderRadius: 8 },
  nextMealFallbackIcon: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: colors.secondarySystemFill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextMealBody: { flex: 1, minWidth: 0 },
  nextMealLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: colors.secondaryLabel,
    textTransform: 'uppercase',
  },
  nextMealRecipeTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '600',
    color: colors.label,
  },
  nextMealDate: { fontSize: 13, lineHeight: 18, color: colors.secondaryLabel },
  nextMealAction: { fontSize: 13, lineHeight: 18, fontWeight: '600', color: colors.blue },
  nextMealError: { fontSize: 16, lineHeight: 21, fontWeight: '600', color: colors.red },
  nextMealSkeleton: { opacity: 0.65 },
  nextMealSkeletonImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: colors.systemFill,
  },
  nextMealSkeletonLabel: {
    width: 112,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.systemFill,
  },
  nextMealSkeletonTitle: {
    width: '72%',
    height: 16,
    borderRadius: 8,
    marginTop: 8,
    backgroundColor: colors.systemFill,
  },
  chip: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: colors.gray5,
  },
  chipActive: { backgroundColor: colors.blue },
  chipText: { fontSize: 13, color: colors.secondaryLabel },
  chipTextSelected: { color: '#ffffff', fontWeight: '600' },
  card: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 8,
  },
  cardImage: {
    width: 100,
    height: 100,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  cardImagePlaceholder: {
    width: 100,
    height: 100,
    backgroundColor: colors.opaqueSeparator,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  cardBody: { flex: 1, padding: 12, justifyContent: 'center' },
  cardTitle: { fontSize: 14, lineHeight: 18, fontWeight: '600', color: colors.label },
  cardTitleMarquee: { marginBottom: 4 },
  cardTags: { fontSize: 12, color: colors.brand, marginBottom: 2, marginTop: 1 },
  cardTagsEmpty: { color: colors.tertiaryLabel },
  cardTagRow: { marginBottom: 2, marginTop: 1 },
  cardTagPill: {
    backgroundColor: colors.brandLight,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  cardTagPillText: { fontSize: 12, lineHeight: 16, color: colors.brand, fontWeight: '500' },
  cardMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  cardHouseholdAvatars: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  cardMeta: { fontSize: 12, color: colors.tertiaryLabel },
  empty: { padding: 40, alignItems: 'center' },
  emptyText: {
    fontSize: 16,
    color: colors.secondaryLabel,
    textAlign: 'center',
    marginBottom: 12,
  },
  searchLoading: { alignItems: 'center', gap: 8, padding: 40 },
  searchLoadingText: { color: colors.secondaryLabel, fontSize: 16, lineHeight: 21 },
  semanticHeader: {
    color: colors.secondaryLabel,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginHorizontal: 16,
    marginTop: 20,
    textTransform: 'uppercase',
  },
  clearFilter: { fontSize: 16, color: colors.blue, fontWeight: '500' },
  favBtn: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  favStar: { fontSize: 20, color: colors.opaqueSeparator },
  favStarActive: { color: '#f59e0b' },
  favChip: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.gray5,
  },
  favChipText: { fontSize: 14, color: colors.secondaryLabel },
  pendingCard: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 8,
    opacity: 0.85,
  },
  pendingImageWrap: {
    width: 100,
    height: 100,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: colors.opaqueSeparator,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  pendingImage: { width: '100%', height: '100%' },
  pendingSpinnerOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    backgroundColor: colors.secondarySystemFill,
    justifyContent: 'center',
  },
  pendingBody: { flex: 1, padding: 12, justifyContent: 'center' },
  pendingTitle: { fontSize: 14, lineHeight: 18, fontWeight: '600', color: colors.label, marginBottom: 4 },
  pendingMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pendingActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pendingCancelWrap: { width: 44, alignItems: 'center', justifyContent: 'center' },
  pendingActionPrimary: { fontSize: 13, color: colors.blue, fontWeight: '600' },
  pendingActionSecondary: { fontSize: 13, color: colors.secondaryLabel },
})
