import { StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'

export const styles = StyleSheet.create({
  headerTitleWrap: { flexDirection: 'row', alignItems: 'center', gap: 8, width: '100%' },
  headerTitleText: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.label,
  },
  headerBtns: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  headerBtn: { paddingHorizontal: 4, paddingVertical: 4 },
  addBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screen: { flex: 1, backgroundColor: colors.secondaryBackground },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  errorText: { color: colors.red, fontSize: 16, textAlign: 'center' },
  tagBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 0,
    paddingBottom: 16,
  },
  tagBarDivider: {
    width: StyleSheet.hairlineWidth,
    height: 20,
    backgroundColor: colors.opaqueSeparator,
    marginHorizontal: 8,
  },
  tagScrollArea: { flex: 1 },
  tagListContent: { gap: 8, paddingRight: 16 },
  chip: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    overflow: 'hidden',
  },
  chipText: { fontSize: 13, color: colors.secondaryLabel },
  chipTextSelected: { color: '#ffffff', fontWeight: '600' },
  card: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 8,
  },
  cardImage: {
    width: 100,
    height: 100,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  cardImagePlaceholder: {
    width: 100,
    height: 100,
    backgroundColor: colors.opaqueSeparator,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  cardBody: { flex: 1, padding: 12, justifyContent: 'center' },
  cardTitle: { fontSize: 14, lineHeight: 18, fontWeight: '600', color: colors.label },
  cardTitleMarquee: { marginBottom: 4 },
  cardTags: { fontSize: 12, color: colors.brand, marginBottom: 2, marginTop: 1 },
  cardTagsEmpty: { color: colors.tertiaryLabel },
  cardTagRow: { marginBottom: 2, marginTop: 1 },
  cardTagPill: {
    backgroundColor: colors.brandLight,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  cardTagPillText: { fontSize: 12, lineHeight: 16, color: colors.brand, fontWeight: '500' },
  cardMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  cardMeta: { fontSize: 12, color: colors.tertiaryLabel },
  empty: { padding: 40, alignItems: 'center' },
  emptyText: {
    fontSize: 16,
    color: colors.secondaryLabel,
    textAlign: 'center',
    marginBottom: 12,
  },
  clearFilter: { fontSize: 16, color: colors.blue, fontWeight: '500' },
  favBtn: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  favStar: { fontSize: 20, color: colors.opaqueSeparator },
  favStarActive: { color: '#f59e0b' },
  favChip: { marginLeft: 16 },
  swipeContainer: { marginHorizontal: 16, marginTop: 8 },
  cardInSwipeable: { marginHorizontal: 0, marginTop: 0 },
  swipeActions: { flexDirection: 'row' },
  swipeEdit: {
    backgroundColor: colors.brand,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeDelete: {
    backgroundColor: colors.red,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  swipeActionText: { color: colors.background, fontSize: 13, fontWeight: '600' },
  pendingCard: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 8,
    opacity: 0.85,
  },
  pendingImageWrap: {
    width: 100,
    height: 100,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: colors.opaqueSeparator,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingBody: { flex: 1, padding: 12, justifyContent: 'center' },
  pendingTitle: { fontSize: 14, lineHeight: 18, fontWeight: '600', color: colors.label, marginBottom: 4 },
  pendingMeta: { fontSize: 12, color: colors.tertiaryLabel },
  pendingSpinnerWrap: { width: 40, alignItems: 'center', justifyContent: 'center' },
})
