import { PlatformColor, StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'
import { DAY_ROW_HEIGHT, MONTH_HEADER_HEIGHT } from './helpers'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loadingOverlay: { position: 'absolute', top: 12, alignSelf: 'center' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  exportBtn: { padding: 4 },
  exportOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'center', alignItems: 'center' },
  list: { flex: 1 },
  listContent: {},
  monthRow: {
    height: MONTH_HEADER_HEIGHT,
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
    paddingBottom: 6,
    backgroundColor: colors.background,
  },
  monthRowLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.tertiaryLabel,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  dayRow: {
    height: DAY_ROW_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
    paddingHorizontal: 16,
  },
  dayRowToday: {
    borderLeftWidth: 3,
    borderLeftColor: colors.blue,
    paddingLeft: 13,
  },
  dayRowLeft: {
    width: 52,
    alignItems: 'center',
  },
  dayRowWeekday: {
    fontSize: 11,
    color: colors.tertiaryLabel,
    fontWeight: '500',
    textTransform: 'uppercase',
  },
  dayRowNum: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.label,
    lineHeight: 24,
  },
  dayRowMonth: {
    fontSize: 10,
    color: colors.tertiaryLabel,
  },
  dayRowTextToday: {
    color: colors.blue,
  },
  dayRowDivider: {
    width: 1,
    height: 36,
    backgroundColor: colors.opaqueSeparator,
    marginHorizontal: 14,
  },
  dayRowContent: { flex: 1 },
  dayRowRecipe: {
    fontSize: 16,
    color: colors.label,
    fontWeight: '500',
  },
  dayRowEmpty: {
    fontSize: 13,
    color: colors.opaqueSeparator,
  },
  dayRowThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    marginLeft: 12,
  },
  dayRowThumbPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    marginLeft: 12,
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
  },
  sheetBackground: { backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string },
  sheetHandle: { backgroundColor: PlatformColor('systemGray3') as unknown as string },
  pickerSearchContainer: {
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 8,
    height: 36,
    borderRadius: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: PlatformColor('systemGray6') as unknown as string,
  },
  pickerSearch: {
    flex: 1,
    paddingVertical: 0,
    fontSize: 16,
    color: PlatformColor('label') as unknown as string,
  },
  removeButton: {
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PlatformColor('systemRed') as unknown as string,
    alignItems: 'center',
  },
  removeButtonText: { color: PlatformColor('systemRed') as unknown as string, fontWeight: '500', fontSize: 16 },
  pickerList: { flex: 1 },
  pickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PlatformColor('separator') as unknown as string,
  },
  pickerItemThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  pickerItemThumbPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
  },
  pickerItemActive: { backgroundColor: colors.brandLight },
  pickerItemText: { flex: 1, fontSize: 16, color: PlatformColor('label') as unknown as string },
  pickerItemTextActive: { color: colors.brand, fontWeight: '600' },
  pickerEmpty: { flex: 1, padding: 40, alignItems: 'center' },
  pickerEmptyText: { fontSize: 16, color: PlatformColor('secondaryLabel') as unknown as string, textAlign: 'center' },
  todayBtn: {
    position: 'absolute',
    right: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    overflow: 'hidden',
  },
  todayBtnText: { color: colors.brandText, fontSize: 16, fontWeight: '600' },
})
