import { PlatformColor, StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  screenBackground: { backgroundColor: colors.background },
  scrollContent: { paddingBottom: 120 },

  // Header back button
  headerBackBtnWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: -8,
    paddingHorizontal: 4,
  },
  headerBackChevron: { marginRight: -4 },
  headerBackBtn: {
    fontSize: 17,
    color: PlatformColor('label') as unknown as string,
  },
  headerEditBtn: { paddingHorizontal: 8, paddingVertical: 4 },
  headerBtns: { flexDirection: 'row', alignItems: 'center' },

  // Quick URL input
  quickUrlSection: { paddingTop: 8, paddingHorizontal: 16, gap: 10 },

  // Method picker
  pickerWrap: { paddingTop: 16, paddingHorizontal: 16, gap: 12 },
  pickerGroup: {
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
    borderRadius: 16,
    borderCurve: 'continuous',
    overflow: 'hidden',
  },
  methodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 14,
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
    minHeight: 64,
  },
  methodRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PlatformColor('separator') as unknown as string,
  },
  methodRowPressed: {
    backgroundColor: PlatformColor('systemFill') as unknown as string,
  },
  methodIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 9,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
  },
  methodTextWrap: { flex: 1 },
  methodTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: PlatformColor('label') as unknown as string,
    marginBottom: 1,
  },
  methodDesc: {
    fontSize: 13,
    color: PlatformColor('secondaryLabel') as unknown as string,
    lineHeight: 17,
  },
  // Input section (common wrapper for all input modes)
  inputSection: { padding: 16, gap: 12 },
  imageLoadingSection: { padding: 16, gap: 16, alignItems: 'center', paddingTop: 60 },

  // URL input
  urlInputGroup: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  urlInput: {
    flex: 1,
    height: 44,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    borderRadius: 999,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: PlatformColor('systemBackground') as unknown as string,
    color: PlatformColor('label') as unknown as string,
  },
  pasteBtn: {
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  pasteBtnText: {
    fontSize: 16,
    color: PlatformColor('secondaryLabel') as unknown as string,
    fontWeight: '500',
  },
  pasteIconBtn: {
    height: 44,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    backgroundColor: PlatformColor('systemBackground') as unknown as string,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pasteIconBtnText: {
    fontSize: 16,
    color: PlatformColor('secondaryLabel') as unknown as string,
    fontWeight: '500',
  },

  // Text paste input
  textInputGroup: { gap: 8 },
  textPasteInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingTop: 11,
    paddingBottom: 11,
    fontSize: 16,
    backgroundColor: PlatformColor('systemBackground') as unknown as string,
    color: PlatformColor('label') as unknown as string,
    minHeight: 200,
    textAlignVertical: 'top',
  },
  textPasteInlineBtn: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  textPasteBtnText: {
    fontSize: 16,
    color: PlatformColor('systemBlue') as unknown as string,
    fontWeight: '500',
  },

  // Share tip card
  shareTipCard: {
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
    borderRadius: 16,
    borderCurve: 'continuous',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  shareTipText: {
    fontSize: 13,
    color: PlatformColor('secondaryLabel') as unknown as string,
    lineHeight: 19,
  },

  // Share URL label (used when share extension delivers a URL)
  shareUrlLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: PlatformColor('secondaryLabel') as unknown as string,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginLeft: 4,
  },

  // Import skeleton
  skeletonBone: {
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
    borderRadius: 6,
  },
  skeletonTitleLine: { height: 26, borderRadius: 8, marginBottom: 8 },
  skeletonTag: { height: 22, borderRadius: 12 },
  skeletonMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  skeletonMetaBox: {
    backgroundColor: colors.secondaryBackground,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    minWidth: 64,
    gap: 4,
  },
  skeletonMetaNumber: { width: 28, height: 17, borderRadius: 5 },
  skeletonMetaLabel: { width: 40, height: 13, borderRadius: 4 },
  skeletonLabel: { width: 90, height: 12, borderRadius: 4, marginBottom: 10 },
  skeletonBullet: { width: 6, height: 6, borderRadius: 3, marginRight: 8, marginTop: 8 },
  skeletonIngredientLine: { height: 17, borderRadius: 5 },
  skeletonStepNum: { width: 20, height: 17, borderRadius: 5, marginRight: 8 },
  skeletonStepLine: { height: 17, borderRadius: 5 },
  skeletonHeroWrap: { alignItems: 'center', justifyContent: 'center' },
  skeletonProgressCard: {
    width: 88,
    height: 88,
    borderRadius: 22,
    backgroundColor: PlatformColor('systemBackground') as unknown as string,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  skeletonProgressTrack: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
    overflow: 'hidden',
  },
  skeletonProgressFill: {
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.brand,
  },

  // Error box
  errorBox: {
    margin: 16,
    backgroundColor: colors.brandLight,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.brand,
  },
  errorTitle: { fontSize: 13, fontWeight: '700', color: colors.brand, marginBottom: 4 },
  errorMsg: { fontSize: 13, color: colors.brand, lineHeight: 18, opacity: 0.8 },
  openInBrowserBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.brand,
  },
  openInBrowserText: { fontSize: 13, fontWeight: '600', color: colors.background },

  // Action bar
  actionBar: {
    flexDirection: 'row',
    gap: 8,
    padding: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('separator') as unknown as string,
    backgroundColor: PlatformColor('systemBackground') as unknown as string,
  },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: { fontSize: 16, color: PlatformColor('secondaryLabel') as unknown as string, fontWeight: '500' },
  primaryBtn: {
    backgroundColor: colors.blue,
    borderRadius: 999,
    overflow: 'hidden',
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
  },
  primaryBtnText: { fontSize: 16, color: '#fff', fontWeight: '600' },
  btnDisabled: { opacity: 0.4 },

  // Read-only import preview (mirrors saved-recipe detail screen)
  previewHeroImage: { width: '100%', aspectRatio: 4 / 3 },
  previewCard: { backgroundColor: colors.background, paddingHorizontal: 16, paddingTop: 20 },
  previewTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: PlatformColor('label') as unknown as string,
    marginBottom: 10,
    lineHeight: 34,
  },
  previewTagRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 12, gap: 6 },
  previewTag: {
    backgroundColor: colors.brandLight,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  previewTagText: { color: colors.brand, fontSize: 12, fontWeight: '500' },
  previewSourceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 12 },
  previewSourceText: { fontSize: 13, color: PlatformColor('secondaryLabel') as unknown as string },
  previewComponentBlock: { marginTop: 8 },
  previewComponentName: {
    fontSize: 20,
    fontWeight: '600',
    color: PlatformColor('label') as unknown as string,
    marginBottom: 12,
    lineHeight: 25,
  },
  previewSection: { marginBottom: 16 },
  previewSectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: PlatformColor('secondaryLabel') as unknown as string,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  previewIngredientRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 6 },
  previewBullet: { color: PlatformColor('tertiaryLabel') as unknown as string, marginRight: 8, marginTop: 1 },
  previewIngredientText: {
    flex: 1,
    fontSize: 17,
    color: PlatformColor('label') as unknown as string,
    lineHeight: 22,
  },
  previewStepRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 14 },
  previewStepNum: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.blue,
    width: 28,
    marginTop: 1,
  },
  previewStepText: {
    flex: 1,
    fontSize: 17,
    color: PlatformColor('label') as unknown as string,
    lineHeight: 22,
  },

  // Edit-mode variants of the preview above (same layout, editable fields)
  previewHeroPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
  },
  previewHeroPlaceholderText: { fontSize: 13, color: PlatformColor('secondaryLabel') as unknown as string },
  previewHeroEditBtn: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  previewHeroEditText: { fontSize: 12, color: '#ffffff', fontWeight: '600' },
  previewTitleInput: {
    borderBottomWidth: 1,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    paddingBottom: 4,
  },
  previewAddTagBtn: {
    borderWidth: 1,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    borderStyle: 'dashed',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  previewAddTagText: { fontSize: 12, color: PlatformColor('secondaryLabel') as unknown as string },
  previewStepEditRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginBottom: 8 },
  previewStepInput: {
    flex: 1,
    fontSize: 17,
    color: PlatformColor('label') as unknown as string,
    lineHeight: 22,
    borderBottomWidth: 1,
    borderColor: PlatformColor('opaqueSeparator') as unknown as string,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },

  // Add row buttons
  addRowBtn: {
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignSelf: 'flex-start',
  },
  addRowBtnText: {
    fontSize: 16,
    color: colors.brand,
    fontWeight: '500',
  },

  stepRemoveBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: PlatformColor('systemRed') as unknown as string,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 3,
  },
  stepRemoveText: { fontSize: 16, color: '#fff', fontWeight: '600', lineHeight: 20 },
})
