import { StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'
import { CARD_RADIUS } from './helpers'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.secondaryBackground },
  content: { paddingBottom: 48 },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 16,
    marginBottom: 4,
    gap: 8,
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statCard: {
    flexBasis: '30%',
    flexGrow: 1,
    backgroundColor: colors.background,
    borderRadius: CARD_RADIUS,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.label,
  },
  statLabel: {
    fontSize: 11,
    color: colors.tertiaryLabel,
    marginTop: 3,
    textAlign: 'center',
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.secondaryLabel,
    marginLeft: 32,
    marginRight: 16,
    marginTop: 24,
    marginBottom: 8,
  },
  card: {
    backgroundColor: colors.background,
    borderRadius: CARD_RADIUS,
    marginHorizontal: 16,
    marginBottom: 4,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  label: { fontSize: 16, color: colors.secondaryLabel },
  value: { fontSize: 16, color: colors.secondaryLabel, maxWidth: '60%' },
  logoutRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'flex-start',
  },
  logoutText: { color: colors.red, fontSize: 16, fontWeight: '500' },
  privacyPolicyText: { color: colors.blue, fontSize: 16 },
  loadingRow: { padding: 24, alignItems: 'center' },
  errorText: { color: colors.red, fontSize: 16, padding: 16 },
  switchLabel: {
    fontSize: 16,
    color: colors.label,
  },
  cardDesc: {
    fontSize: 12,
    color: colors.tertiaryLabel,
    marginTop: 2,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  pickerLabel: { fontSize: 16, color: colors.label },
  pickerRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  pickerValue: { fontSize: 16, color: colors.secondaryLabel },
  pickerChevron: { fontSize: 20, color: colors.tertiaryLabel, lineHeight: 22 },
  switchRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  switchRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  switchLabelBlock: { flex: 1, marginRight: 12 },
  householdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  householdRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  householdDot: { width: 14, height: 14, borderRadius: 7 },
  householdInfo: { flex: 1 },
  householdName: { fontSize: 16, fontWeight: '500', color: colors.label },
  householdActive: { fontSize: 12, color: colors.blue, marginTop: 1 },
  manageBtn: {
    paddingHorizontal: 4,
    paddingVertical: 6,
  },
  manageBtnText: { fontSize: 16, fontWeight: '400', color: colors.blue },
  newHouseholdRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.separator,
  },
  newHouseholdText: { fontSize: 16, color: colors.blue, fontWeight: '500' },
  emptyHouseholds: {
    fontSize: 16,
    color: colors.tertiaryLabel,
    padding: 16,
    textAlign: 'center',
  },
  allergenPad: { padding: 16 },
  scopeLabel: { fontSize: 12, color: colors.tertiaryLabel, marginBottom: 4 },
  allergenDisclaimer: { fontSize: 13, lineHeight: 18, color: colors.tertiaryLabel, marginBottom: 12 },
  accordionBlock: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.separator,
    marginTop: 4,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  accordionLabel: { fontSize: 16, fontWeight: '500', color: colors.secondaryLabel },
  accordionChevron: { fontSize: 10, color: colors.tertiaryLabel },
  accordionBody: { paddingBottom: 12 },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 8,
    gap: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: colors.opaqueSeparator,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  checkboxSelected: { backgroundColor: colors.blue, borderColor: colors.blue },
  checkmark: { color: colors.background, fontSize: 12, fontWeight: '700' },
  checkContent: { flex: 1 },
  checkLabel: { fontSize: 16, color: colors.label },
  checkDesc: { fontSize: 12, color: colors.tertiaryLabel, marginTop: 1 },
  saveBtn: {
    backgroundColor: colors.blue,
    borderRadius: CARD_RADIUS,
    paddingVertical: 11,
    alignItems: 'center',
    marginTop: 16,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: colors.background, fontSize: 16, fontWeight: '600' },
  reanalyzeBtn: {
    backgroundColor: colors.secondaryBackground,
    borderRadius: CARD_RADIUS,
    paddingVertical: 11,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.opaqueSeparator,
  },
  reanalyzeBtnText: { color: colors.secondaryLabel, fontSize: 16, fontWeight: '600' },
})
